# Generated by Django 5.2.16 on 2026-08-04 02:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0003_event_employer_reimbursable_event_tax_relevant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerDiemCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_codes', models.JSONField(default=list)),
                ('daily_amounts', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('complete', models.BooleanField()),
                ('missing_facts', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('derivation_hash', models.CharField(max_length=64, unique=True)),
                ('activity_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.event')),
                ('input_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.eventrevision')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('jurisdiction', models.CharField(max_length=10)),
                ('rule_type', models.CharField(max_length=50)),
                ('values', models.JSONField(default=dict)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_citation', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['effective_from', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='tax_rule_dates_ordered')],
            },
        ),
    ]
