# Generated by Django 5.2.16 on 2026-08-04 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_seed_2026_rules'),
        ('travel', '0004_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDistance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=30)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('version', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('provider_input', models.JSONField(default=dict)),
                ('provider_response', models.JSONField(default=dict)),
                ('raw_response_hash', models.CharField(blank=True, max_length=64)),
                ('returned_metres', models.PositiveBigIntegerField(blank=True, null=True)),
                ('full_tax_km', models.PositiveIntegerField(blank=True, null=True)),
                ('calculation_date', models.DateField()),
                ('manual_override', models.BooleanField(default=False)),
                ('override_comment', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_destinations', to='travel.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_origins', to='travel.location')),
            ],
            options={
                'ordering': ['origin_id', 'destination_id', 'mode', 'version'],
                'constraints': [models.UniqueConstraint(fields=('origin', 'destination', 'mode', 'version'), name='unique_route_distance_version'), models.CheckConstraint(condition=models.Q(('distance_km__gte', 0)), name='route_distance_nonnegative')],
            },
        ),
    ]
