# Generated by Django 5.2.16 on 2026-08-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_postgres_tax_fact_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedistance',
            name='override_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
