# Generated by Django 5.2.16 on 2026-08-04 02:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_postgres_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('relative_original_path', models.CharField(max_length=1000, unique=True)),
                ('relative_preview_path', models.CharField(blank=True, max_length=1000)),
                ('relative_thumbnail_path', models.CharField(blank=True, max_length=1000)),
                ('supplied_content_type', models.CharField(blank=True, max_length=255)),
                ('detected_mime_type', models.CharField(max_length=255)),
                ('detected_format', models.CharField(max_length=20)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField()),
                ('preview_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('preview_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='evidence.attachment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_links', to='ledger.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attachment', 'event', 'link_type'), name='unique_attachment_link')],
            },
        ),
    ]
