# Generated by Django 5.2.16 on 2026-08-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('sha256', 'size_bytes'), name='unique_attachment_bytes'),
        ),
    ]
