# Generated by Django 5.2.16 on 2026-08-04 03:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0004_postgres_audit_hardening'),
        ('travel', '0003_externalactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('xlsx', 'Excel workbook'), ('sqlite', 'Portable SQLite'), ('full_zip', 'Complete ZIP')], max_length=20)),
                ('range_start', models.DateField()),
                ('range_end', models.DateField()),
                ('as_of', models.DateTimeField()),
                ('relative_path', models.CharField(max_length=1000, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('relative_package_path', models.CharField(blank=True, max_length=1000)),
                ('package_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travel.employer')),
            ],
            options={
                'ordering': ['-period_end', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inclusion_reason', models.CharField(default='Employer reimbursement', max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_memberships', to='ledger.event')),
                ('included_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.eventrevision')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_events', to='exports.employerpackage')),
            ],
            options={
                'ordering': ['event_id'],
            },
        ),
        migrations.AddField(
            model_name='employerpackage',
            name='events',
            field=models.ManyToManyField(related_name='employer_packages', through='exports.PackageEvent', to='ledger.event'),
        ),
        migrations.CreateModel(
            name='PackageStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='exports.employerpackage')),
                ('status_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ledger.event')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='packageevent',
            constraint=models.UniqueConstraint(fields=('package', 'event'), name='unique_event_per_package'),
        ),
        migrations.AddConstraint(
            model_name='employerpackage',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='employer_package_valid_period'),
        ),
    ]
