# Generated by Django 5.2.16 on 2026-08-04 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportartifact',
            name='kind',
            field=models.CharField(choices=[('xlsx', 'Excel workbook'), ('csv', 'CSV'), ('json', 'JSON'), ('sqlite', 'Portable SQLite'), ('full_zip', 'Complete ZIP')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('xlsx', 'Excel workbook'), ('csv', 'CSV'), ('json', 'JSON'), ('sqlite', 'Portable SQLite'), ('full_zip', 'Complete ZIP')], max_length=20)),
                ('range_start', models.DateField()),
                ('range_end', models.DateField()),
                ('as_of', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('artifact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job', to='exports.exportartifact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
