# Generated by Django 5.2.16 on 2026-08-04 01:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('work_from_home', 'Work from home'), ('journey', 'Journey'), ('work_location', 'Work location'), ('external_activity', 'External activity'), ('expense', 'Expense'), ('receipt_only', 'Receipt only'), ('reimbursement_update', 'Reimbursement update'), ('note', 'Note')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('effective_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('snapshot', models.JSONField(default=dict)),
                ('complete', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('previous_audit_hash', models.CharField(blank=True, max_length=64)),
                ('audit_hash', models.CharField(max_length=64, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='ledger.event')),
                ('parent_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_revisions', to='ledger.eventrevision')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_events', to='ledger.eventrevision'),
        ),
        migrations.AddConstraint(
            model_name='eventrevision',
            constraint=models.UniqueConstraint(fields=('event', 'revision_number'), name='unique_event_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='eventrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='revision_number_positive'),
        ),
    ]
