# Generated by Django 5.2.16 on 2026-08-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_postgres_immutability'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='employer_reimbursable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='tax_relevant',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
