# Generated by Django 5.2.16 on 2026-08-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_postgres_audit_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('work_from_home', 'Work from home'), ('journey', 'Journey'), ('work_location', 'Work location'), ('external_activity', 'External activity'), ('expense', 'Expense'), ('receipt_only', 'Receipt only'), ('attachment_upload', 'Attachment upload'), ('reimbursement_update', 'Reimbursement update'), ('note', 'Note')], max_length=32),
        ),
    ]
