# Generated by Django 5.2.16 on 2026-08-04 02:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='single_active_employer')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('residence', 'Residence'), ('first_workplace', 'First workplace'), ('employer_office', 'Another employer office'), ('client_site', 'Client site'), ('other_external', 'Other external location')], max_length=32)),
                ('address', models.TextField(blank=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('station_name', models.CharField(blank=True, max_length=200)),
                ('is_default_residence', models.BooleanField(default=False)),
                ('is_favourite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_residence', True)), fields=('is_default_residence',), name='single_default_residence')],
            },
        ),
    ]
