# Generated by Django 5.2.16 on 2026-08-04 02:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pass_type', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attachment_event_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-valid_from', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='rail_pass_dates_ordered')],
            },
        ),
    ]
