# Generated by Django 5.2.16 on 2026-08-04 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_event_employer_reimbursable_event_tax_relevant'),
        ('travel', '0002_railpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalActivity',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='external_activity_identity', serialize=False, to='ledger.event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
