# Generated by Django 5.2.16 on 2026-08-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_externalactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
