# Generated by Django 5.2.16 on 2026-08-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_postgres_audit_hardening'),
        ('travel', '0004_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalactivity',
            name='journey_legs',
            field=models.ManyToManyField(blank=True, related_name='linked_external_activities', to='ledger.event'),
        ),
    ]
