# Generated by Django 5.2.16 on 2026-08-04 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_postgres_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='expense_identity', serialize=False, to='ledger.event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
