# Generated by Django 5.2.16 on 2026-08-04 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reimbursement_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], default='not_applicable', max_length=20),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('code', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='expenses.expensecategory')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.CreateModel(
            name='ReimbursementStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement_history', to='expenses.expense')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
