# Generated by Django 5.2.16 on 2026-08-04 04:21

from django.db import migrations, models


def rename_pending_to_ready(apps, schema_editor):
    apps.get_model("expenses", "Expense").objects.filter(
        reimbursement_status="pending"
    ).update(reimbursement_status="ready")
    apps.get_model("expenses", "ReimbursementStatusChange").objects.filter(
        new_status="pending"
    ).update(new_status="ready")


def suspend_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            DROP TRIGGER IF EXISTS workledger_expense_status_audited ON expenses_expense;
            DROP TRIGGER IF EXISTS workledger_reimbursement_history_immutable
              ON expenses_reimbursementstatuschange;
            """
        )


def reinstate_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE OR REPLACE FUNCTION workledger_validate_expense_status_change()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $function$
            DECLARE
                latest_previous text;
                latest_new text;
                latest_amount numeric;
            BEGIN
                IF OLD.reimbursement_status IS DISTINCT FROM NEW.reimbursement_status
                   OR OLD.reimbursed_amount IS DISTINCT FROM NEW.reimbursed_amount THEN
                    SELECT previous_status, new_status, new_reimbursed_amount
                    INTO latest_previous, latest_new, latest_amount
                    FROM expenses_reimbursementstatuschange
                    WHERE expense_id = NEW.event_id
                    ORDER BY changed_at DESC, id DESC
                    LIMIT 1;
                    IF latest_previous IS DISTINCT FROM OLD.reimbursement_status
                       OR latest_new IS DISTINCT FROM NEW.reimbursement_status
                       OR latest_amount IS DISTINCT FROM NEW.reimbursed_amount THEN
                        RAISE EXCEPTION 'expense update requires matching reimbursement history'
                            USING ERRCODE = '55000';
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $function$;
            CREATE TRIGGER workledger_reimbursement_history_immutable
            BEFORE UPDATE OR DELETE ON expenses_reimbursementstatuschange
            FOR EACH ROW EXECUTE FUNCTION workledger_reject_reimbursement_history_mutation();
            CREATE TRIGGER workledger_expense_status_audited
            BEFORE UPDATE ON expenses_expense
            FOR EACH ROW EXECUTE FUNCTION workledger_validate_expense_status_change();
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_postgres_reimbursement_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reimbursed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reimbursementstatuschange',
            name='new_reimbursed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reimbursementstatuschange',
            name='previous_reimbursed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(suspend_guards, migrations.RunPython.noop),
        migrations.RunPython(rename_pending_to_ready, migrations.RunPython.noop),
        migrations.RunPython(reinstate_guards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expense',
            name='reimbursement_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('draft', 'Draft'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('partially_reimbursed', 'Partially reimbursed'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='not_applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='reimbursementstatuschange',
            name='new_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('draft', 'Draft'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('partially_reimbursed', 'Partially reimbursed'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=24),
        ),
    ]
